### ISSUE TITLE
Silently fails in Edge

### ISSUE THREAD

**Issue by David-Mulder** [GoogleWebComponents/google-signin#117] opened 2015-11-15 16:47 UTC
Neither the demo page or the element itself seems to work in Edge. Not seeing any errors either. And third party cookies are *not* blocked.

**Comment by atotic** [comment] 2015-11-15 21:34
In what way does it fail? I've tried the demo on Edge, and it pops up the confirmation dialog. 

I was unable verify it all the way, because I run elements on my Mac, and Edge inside a VM, and oauth does not want to authenticate to anything but a localhost:8080. Are you sure you are not running in the oauth/hostname problems?

**Comment by David-Mulder** [comment] 2015-11-15 22:20
@atotic The demo page running on https://elements.polymer-project.org/elements/google-signin?view=demo:demo/index.html&active=google-signin actually authenticates just fine from the oauth point of view. In Edge however after you log in in the dialog it won't change the state of the element (it will keep on showing the button in blue rather than gray and clicking it again will give you a short flash of the dialog and then do nothing again)

**Comment by atotic** [comment] 2015-11-16 05:04
Confirmed on my windows box. I suspect an error in oauth2 library.
We call promise = gapi.auth2.getAuthInstance().signIn(params);
and the promise never resolves: neither success nor fail callbacks get called.

@addyosmani can you assign this to someone who can debug oauth2?

**Comment by ebidel** [comment] 2015-11-16 22:37
@gguuss is this related to the known  Edge bug?

**Comment by gguuss** [comment] 2015-11-23 17:04
This might be, we pushed a fix on Friday to work around the IE11/Edge localstorage bug, this may have fixed it.

**Comment by atotic** [comment] 2015-11-23 17:21
Bingo! Tested, and it works.

**Closed by atotic** 2015-11-23 17:21 UTC

**Comment by ebidel** [comment] 2015-11-23 19:58
Love it when API fixes close our bugs :)
