### ISSUE TITLE
Broadcast initilized event

### ISSUE THREAD

**Issue by filipproch** [GoogleWebComponents/google-signin#121] opened 2016-02-01 09:57 UTC
It's not always best for us to observe on signedIn, because you are setting it initially to false before it is really determined. In my application, I display loading screen which should wait to detect whether user is authenticated a then display screen accordingly, which is by observing `signedIn` not easy to handle. I suggest adding event which is emmited in `handleUserUpdate` if it is the first time this method is called, after changing the signedIn property so we can handle above case properly.

**Comment by soonick** [comment] 2017-01-16 15:02
Hello @atotic, @Zoramite,

I just started trying to use this component and found myself having the same problem as @filipproch. I see that there has been a pull request that can solve the issue for a couple months but no comments have been made on it. Do you think you can help us look at the pull request and let us know how to proceed?

**Comment by atotic** [comment] 2017-01-17 08:26
Apologies for not looking at this, I am no longer working on google-signin, so I can't help you. @ebidel ?

I understand your problem, you want to know when signedIn value has been initialized to its stable state.
The problem is caused by signedIn being a boolean, while it really can be in 3 states: unknown, signedIn, or signedOut.
The proposed patch adds another property: `initialized`.
Personally, I'd prefer just to make signedIn a Number, representing three states, 

But that is a compatibility-breaking change. Maybe add a signedInVerbose property that is tri-state? 1 for signedIn, 0 for signedOut, -1 for uninitialized, and point new API users towards using it instead of signedIn?

**Comment by filipproch** [comment] 2017-01-17 08:46
The usage of another property approach is also used in Polymerfire library, where you have "statusKnown" property. (https://github.com/firebase/polymerfire/blob/master/firebase-auth.html)

As it would be breaking changes to change the type of signedIn, I personally think it would be better to add another property than to introduce another confusing property and thus having 'signedIn' and 'signedInVerbose'.

Anyway, any solution to this problem would be appreciated

**Comment by soonick** [comment] 2017-01-19 14:56
@ebidel can you help us with this?

**Comment by soonick** [comment] 2017-01-24 05:23
@ebidel sorry for pinging you again, but I would really like to use this component and I can't use it without this feature. Can you help us?

**Comment by filipproch** [comment] 2017-01-24 05:58
@soonick Then fork it, modify it and use your modified component, you can also send a pull request if you think it would be appropriate

**Comment by soonick** [comment] 2017-01-24 06:39
@filipproch. I want to leave forking it as a last resort. We already have a pull request: #153

**Comment by filipproch** [comment] 2017-01-24 06:45
@soonick I know, just saying you don't have to wait for @ebidel to merge the pull request, if you really need it, that's what open source gives you

**Comment by atotic** [comment] 2017-01-24 21:46
Change has been merged.

**Closed by atotic** 2017-01-24 21:46 UTC
Labels: enhancement

**Comment by soonick** [comment] 2017-01-25 01:26
Thank you :)

**Comment by atotic** [comment] 2017-01-25 08:02
👍
